# Generated by Django 2.2.1 on 2019-05-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='User Name', max_length=255)),
                ('image_path', models.CharField(help_text='Print Image path', max_length=255)),
                ('is_clockedIn', models.BooleanField(default=False, help_text='Check for Clock in or out')),
                ('clockin_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('clockout_on', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockin', models.DateTimeField(help_text='Clock In datetime')),
                ('clockout', models.DateTimeField(help_text='Clock In datetime')),
                ('user', models.ForeignKey(help_text='PrintUser', on_delete=django.db.models.deletion.CASCADE, to='Engine.PrintUser')),
            ],
        ),
    ]
