# Generated by Django 2.2.1 on 2019-05-20 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocks',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2019, 5, 20, 19, 40, 52, 648550, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printuser',
            name='clockin_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printuser',
            name='clockout_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
