# Generated by Django 2.2.1 on 2019-05-21 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0002_auto_20190520_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clocks',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='printuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
